# Generated by Django 6.0.2 on 2026-03-01 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_options_client_address_client_document_and_more'),
        ('vehicles', '0002_alter_vehicle_options_vehicle_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total')),
                ('payment_method', models.CharField(choices=[('Credit_Card', 'Cartão de Crédito'), ('Debit_Card', 'Cartão de Débito'), ('Bank_Slip', 'Boleto Bancário'), ('Pix', 'Pix'), ('Cash', 'Dinheiro em Espécie')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pendente'), ('Done', 'Concluída'), ('Canceled', 'Cancelada')], default='Pending', max_length=20, verbose_name='Status da Venda')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
