# Generated by Django 6.0.2 on 2026-03-01 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_client_address_client_document_and_more'),
        ('sales', '0001_initial'),
        ('vehicles', '0002_alter_vehicle_options_vehicle_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
