# Generated by Django 6.0.2 on 2026-03-02 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Relatório')),
                ('report_type', models.CharField(choices=[('sales', 'Vendas'), ('clients', 'Clientes'), ('vehicles', 'Veículos'), ('performance', 'Performance')], max_length=20, verbose_name='Tipo')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10, verbose_name='Formato')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parâmetros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Arquivo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório Salvo',
                'verbose_name_plural': 'Relatórios Salvos',
                'ordering': ['-created_at'],
            },
        ),
    ]
